import PDFDocument from 'pdfkit';

interface Medicine {
    name: string;
    dosage: string;
    duration: string;
}

interface PrescriptionData {
    patientName: string;
    doctorName: string;
    date: string;
    medicines: Medicine[];
    instructions?: string;
    aiInsights?: string;
    riskLevel?: string;
}

/**
 * Generates a PDF buffer using pdfkit format.
 * 
 * @param {PrescriptionData} data - All the textual data needed for the PDF.
 * @returns {Promise<Buffer>} - The assembled PDF buffer.
 */
export const generatePrescriptionPDF = (data: PrescriptionData): Promise<Buffer> => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const chunks: Buffer[] = [];

            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', (err) => reject(err));

            // Header
            doc.fontSize(24).font('Helvetica-Bold').text('AI Clinic', { align: 'center' });
            doc.fontSize(10).font('Helvetica').text('Smart Diagnosis & Prescription System', { align: 'center' });
            doc.moveDown(2);

            // Patient Details
            doc.fontSize(12).font('Helvetica-Bold').text('Patient Information:');
            doc.font('Helvetica').text(`Patient Name: ${data.patientName}`);
            doc.text(`Consultant: Dr. ${data.doctorName}`);
            doc.text(`Date of Visit: ${data.date}`);
            doc.moveDown(2);

            // AI Diagnosis Section (if provided)
            if (data.aiInsights || data.riskLevel) {
                doc.fontSize(14).font('Helvetica-Bold').fillColor('#2b6cb0').text('AI Smart Diagnosis Analysis');
                doc.fillColor('black');

                if (data.riskLevel) {
                    doc.fontSize(10).font('Helvetica-Bold').text(`Assessed Risk Level: ${data.riskLevel}`);
                }

                if (data.aiInsights) {
                    doc.fontSize(10).font('Helvetica').text(`Notes: ${data.aiInsights}`);
                }

                doc.moveDown(1.5);
            }

            // Medicines Table-like Structure
            doc.fontSize(14).font('Helvetica-Bold').fillColor('black').text('Prescribed Medicines');
            doc.moveDown(0.5);

            data.medicines.forEach((med, index) => {
                doc.fontSize(11).font('Helvetica-Bold').text(`${index + 1}. ${med.name}`);
                doc.fontSize(10).font('Helvetica').text(`    Dosage: ${med.dosage} | Duration: ${med.duration}`);
                doc.moveDown(0.5);
            });

            doc.moveDown(1.5);

            // Special Instructions
            if (data.instructions) {
                doc.fontSize(12).font('Helvetica-Bold').text('Special Instructions:');
                doc.fontSize(10).font('Helvetica').text(data.instructions);
            }

            // Footer
            doc.moveDown(4);
            doc.fontSize(10).font('Helvetica-Oblique').text('This document was generated by AI Clinic Management System.', { align: 'center' });
            doc.text('Valid electronically without physical signature.', { align: 'center' });

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};
