import { parentPort, workerData } from 'worker_threads';
import PDFDocument from 'pdfkit';

const generate = async () => {
    try {
        const data = workerData;
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => {
             const result = Buffer.concat(chunks);
             parentPort?.postMessage({ type: 'SUCCESS', buffer: result });
        });
        doc.on('error', (err) => {
             parentPort?.postMessage({ type: 'ERROR', error: err.message });
        });

        // Header
        doc.fontSize(24).font('Helvetica-Bold').text('AI Clinic', { align: 'center' });
        doc.fontSize(10).font('Helvetica').text('Smart Diagnosis & Prescription System', { align: 'center' });
        doc.moveDown(2);

        // Patient Details
        doc.fontSize(12).font('Helvetica-Bold').text('Patient Information:');
        doc.font('Helvetica').text(`Patient Name: ${data.patientName}`);
        doc.text(`Consultant: Dr. ${data.doctorName}`);
        doc.text(`Date of Visit: ${data.date}`);
        doc.moveDown(2);

        // AI Diagnosis Section (if provided)
        if (data.aiInsights || data.riskLevel) {
            doc.fontSize(14).font('Helvetica-Bold').fillColor('#2b6cb0').text('AI Smart Diagnosis Analysis');
            doc.fillColor('black');

            if (data.riskLevel) {
                doc.fontSize(10).font('Helvetica-Bold').text(`Assessed Risk Level: ${data.riskLevel}`);
            }

            if (data.aiInsights) {
                doc.fontSize(10).font('Helvetica').text(`Notes: ${data.aiInsights}`);
            }

            doc.moveDown(1.5);
        }

        // Medicines Table-like Structure
        doc.fontSize(14).font('Helvetica-Bold').fillColor('black').text('Prescribed Medicines');
        doc.moveDown(0.5);

        if (Array.isArray(data.medicines)) {
            data.medicines.forEach((med: any, index: number) => {
                doc.fontSize(11).font('Helvetica-Bold').text(`${index + 1}. ${med.name}`);
                doc.fontSize(10).font('Helvetica').text(`    Dosage: ${med.dosage} | Duration: ${med.duration}`);
                doc.moveDown(0.5);
            });
        }

        doc.moveDown(1.5);

        // Special Instructions
        if (data.instructions) {
            doc.fontSize(12).font('Helvetica-Bold').text('Special Instructions:');
            doc.fontSize(10).font('Helvetica').text(data.instructions);
        }

        // Footer
        doc.moveDown(4);
        doc.fontSize(10).font('Helvetica-Oblique').text('This document was generated by AI Clinic Management System.', { align: 'center' });
        doc.text('Valid electronically without physical signature.', { align: 'center' });

        doc.end();
    } catch (error) {
         parentPort?.postMessage({ type: 'ERROR', error: (error as Error).message });
    }
};

generate();
